config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    get 'new', to: 'home#new', as: :new_home
    resources :groups do
      resources :depenses
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_depenses
  has_many :depenses, through: :group_depenses # Change this line
  validates :name, presence: true
  validates :icon, presence: true
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def show
    @group = Group.find(params[:id])
    @depenses = @group.depenses.order(created_at: :desc)
  end

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def authenticate_user!
    return if user_signed_in?

    redirect_to new_user_session_path
  end

  def create
    @group = current_user.groups.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/new.html.erb
<div class="main_container col-6">
<div class="header_element d-flex justify-content-between align-items-center  p-2 mb-4">
<%= link_to root_path  do %>
  <i class="bi bi-arrow-left text-white h3"></i>
<% end %>
<h2>New Group</h2>
  <div class="actions text-center mt-3">
    <i class="bi bi-search h3"></i>
  </div>
</div>
<%= form_with model: @group, url: groups_path, method: :post do |form| %>
    <div class="form-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :icon, class: "form-label" %>
      <%= form.text_field :icon, class: "form-control" %>
    </div>
    <div class="actions text-center mt-3">
        <%= form.submit "Create Group", class: "btn btn-primary " %>
    </div>
<% end %>
</div>

app/views/groups/show.html.erb
<div class="main_container col-6">
<div class="header_element d-flex justify-content-between align-items-center  p-2 mb-4">
<%= link_to root_path  do %>
  <i class="bi bi-arrow-left text-white h3"></i>
<% end %>
<% total_depenses = @group.depenses.sum(:amount) %>
<h3>TOTAL: $<%= total_depenses > 0 ? total_depenses : 0 %></h3>
  <div class="actions text-center mt-3">
    <i class="bi bi-search h3"></i>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-12">
      <div class="card">
        <div class="card-body">
        <div class="d-flex  align-items-center">
          <img src="<%= @group.icon %>" alt="Group Icon" class="bi-image p-2" style="max-width: 100px;">
          <h5 class="card-title p-2"><%= @group.name %></h5>
        </div>

          <h6 class="card-subtitle mb-2 text-muted p-2">Depenses:</h6>
          <% if @depenses.any? %>
            <ul>
              <% @depenses.each do |depense| %>
                <li class="depenseList p-3">
                <p class='grisColor'><%= depense.name %> - <%= depense.amount %>$</p>
                <% formatted_depense_date = depense.created_at.strftime("%e, %B %Y at %I:%M%P") %>
                  <div>
                  <i class="bi bi-calendar h3"></i>
                  <span class="smallSpan grisColor"><%= formatted_depense_date %></span>
                  </div>
                  </li>
              <% end %>
            </ul>
          <% else %>
            <p>No Depenses for this group.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  <% if user_signed_in? %>
    <div class="container addBtn actions text-center mt-3 fixed-bottom  mx-auto py-3 col-5">
        <%= link_to new_group_depense_url(@group)  do %>
      <button type="button" class="btn col-11   border-white text-white" >
        Add Depense
      </button>
    <% end %>
    </div>
  <% end %>
</div>