config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    get 'new', to: 'home#new', as: :new_home
    resources :groups do
      resources :depenses
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    return unless user_signed_in?

    @user_groups = current_user.groups # Retrieve the current user's groups
    render 'new'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="main_container col-6">
  <div class="col-12 d-flex flex-column p-4 fullheight justify-content-center align-items-center">
    <div class="title_el">
  <h1 >Kondona</h1>
    </div>
    <div class="col-12 form-group mb-2">
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-block col-12 p-2' %>
    </div>
    <div class="col-12 mb-2">
      <%= link_to 'Register', new_user_registration_path, class: 'btn  btn-lg btn-block col-12 grisColor register_btn' %>
    </div>
  </div>
</div>

app/views/home/new.html.erb
<div class="main_container col-6">
  <div class="header_element d-flex justify-content-between align-items-center  p-2 mb-4">
    <button type="button" class="btn " data-bs-toggle="offcanvas" data-bs-target="#menu" aria-controls="menu">
      <i class="bi bi-list h3 text-white"></i>
    </button>
    <div class="offcanvas offcanvas-start bg-dark" tabindex="-1" id="menu" aria-labelledby="menuLabel">
    <div class="col-12 d-flex justify-content-end"align-items-center">
      <button type="button" class=" m-2 btn-close text-reset bg-white  data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
      <div class="offcanvas-header">
          <div class="col-12 d-flex justify-content-center align-items-center">
            <img src="<%= current_user.image %>" alt="Group Icon" class="bi-image" style="max-width: 100px;">
          </div>
      </div>
      <div class="offcanvas-body">
    <div class="actions text-center mt-3">
      <%= form_tag destroy_user_session_path, method: :delete, class: "d-inline" do %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
      <% end %>
    </div>
      </div>
    </div>
    <h2>Depenses</h2>
      <div class="actions text-center mt-3">
    <i class="bi bi-search h3"></i>
  </div>
  </div>
  <div class="container">
    <div class="container justify-content-center removedecoration">
      <% if @user_groups.present? %>
        <% @user_groups.each do |group| %>
          <%= link_to group_path(group) do %>
            <div class="col-md-12 my-2">
              <div class="card">
                <div class="card-body d-flex flex-row justify-content-between align-items-center">
                  <div class="col-3">
                    <img src="<%= group.icon %>" alt="Group Icon" class="bi-image" style="max-width: 100px;">
                  </div>
                  <div class="col-6 grisColor">
                    <h5 class="card-title "><%= group.name %></h5>
                    <% formatted_date = group.created_at.strftime("%e, %B %Y") %>
                    <span class="smallSpan"><%= formatted_date %></span>
                  </div>
                  <div class="col-3 blackColor">
                    <% total_depenses = group.depenses.sum(:amount) %>
                    <h3>$<%= total_depenses > 0 ? total_depenses : 0 %></h3>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% else %>
        <div class="col-md-12 text-center">
          <p>No groups available.</p>
        </div>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="container addBtn actions text-center mt-3 fixed-bottom mx-auto py-3 col-5">
        <%= link_to new_group_url  do %>
      <button type="button" class="btn col-11 text-white  border-white" >
        Create New Group
      </button>
    <% end %>
    </div>
  <% end %>
</div>