config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    get 'new', to: 'home#new', as: :new_home
    resources :groups do
      resources :depenses
    end
  end
end

app/controllers/depenses_controller.rb
class DepensesController < ApplicationController
  before_action :set_group, :authenticate_user!

  def new
    @depenses = @group.depenses
    @depense = Depense.new
  end

  def create
    @depense = Depense.new(depense_params)
    @depense.user = current_user
    @group_depense = GroupDepense.new(group: @group, depense: @depense)
    if @group_depense.save
      redirect_to group_path(@group), notice: 'Depense was successfully added.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def depense_params
    params.require(:depense).permit(:name, :amount)
  end
end

app/helpers/depenses_helper.rb
module DepensesHelper
end

app/views/depenses/new.html.erb
<div class="main_container col-6">
<div class="header_element d-flex justify-content-between align-items-center  p-2 mb-4">
<%= link_to group_path(@group)  do %>
  <i class="bi bi-arrow-left text-white h3"></i>
<% end %>

<h4>Add Depense to <%= @group.name %></h4>
  <div class="actions text-center mt-3">
    <i class="bi bi-search h3"></i>
  </div>
</div>
<%= form_with(model: @depense, url: group_depenses_path(@group), method: :post, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :amount, class: "form-label" %>
      <%= form.text_field :amount, class: "form-control", type: :number %>
    </div>
    <div class="actions text-center mt-3">
        <%= form.submit "Add Depense", class: "btn btn-primary" %>
    </div>
<% end %>
</div>